frame_to_j2000 – moonframe
frame_to_j2000 Function
6 statements
Source File
private function frame_to_j2000(me, et) result(rot)
rotation matrix from the frame to j2000
Type Bound
moon_frame_interpolater
Arguments
Type Intent Optional Attributes Name
class(moon_frame_interpolater), intent(inout) :: me
real(kind=wp), intent(in) :: et
Return Value real(kind=wp), (3,3)
Calls
Source Code
    function frame_to_j2000(me, et) result(rot)
        !! rotation matrix from the frame to j2000
        class(moon_frame_interpolater), intent(inout) :: me
        real(wp), intent(in) :: et
        real(wp) :: rot(3, 3)
        rot = transpose(me%j2000_to_frame(et))
    end function frame_to_j2000
Call graph
frame_to_j2000 calls j2000_to_frame
j2000_to_frame calls evaluate, rpy_to_rot